### PR TITLE
Added link to /providers from Sponsorships Page (#15)

### PR DESCRIPTION
**Pull request by rohnsha0**
as discussed in #15

### CODE REVIEW

**Comment by stevepiercy** [comment]
@plone/marketing-communications should this repository require that every pull request have an approval from someone that is not the PR author before it is merged, unless the author is an Admin?

**Comment by rohnsha0** [comment]
@stevepiercy Same I thought!

**Comment by mtrebron** [comment]
I believe changes to this repo should be initiated/discussed/guided/coordinated by members of the various Plone Community teams. @ronsha0 see https://plone.org/community on joining the community.

**Comment by rohnsha0** [comment]
@mtrebron @stevepiercy I apologise for this PR!
But the issue was raised in plone/CMFPlone repo

**Comment by rohnsha0** [comment]
@stevepiercy @mtrebron I apologise for the PR!
But I thought it might be a valid issue.... Sir!

**Comment by rohnsha0** [comment]
And a small change... So directly merged... Else I've not merged any of the PR without any discussion... :)

**Comment by stevepiercy** [comment]
I have no availability to join the @teams/marketing-communications team. The documentation team keeps me very busy.

Anyway, I've sent them my concern by `@`-ing that team. Now it's in their hands to take up whether they want to configure this repo to disallow merging by non-members of their team.

**Comment by mtrebron** [comment]
@stevepiercy my comment was directed at @rohnsha0 - sorry for confusion. 
@rohnsha0 I applaud your enthousiasm, please join the Plone Community forums: https://community.plone.org/

**Comment by rohnsha0** [comment]
Thanks! @mtrebron 
I've created my account! 
Waiting for approval......

**Comment by mauritsvanrees** [comment]
> I've created my account!
> Waiting for approval......

I have approved.

**Pull request merged**
